### ISSUE TITLE
Impossible to change active tab styles

### ISSUE THREAD

**Issue by maryia-kabash** [artf/grapesjs-tabs#2]
There is no way to change active tab styling as `classTabActive` is not added to the class list. It can be done manually, but it's not obvious for users.

**Comment by artf** [comment]
Probably we need [something like a button we used in the tooltip plugin](https://github.com/artf/grapesjs-tooltip/blob/689ff92f84819f72251a062855bc6dd63e55735e/src/components.js#L206-L219)

**Comment by maryia-kabash** [comment]
@artf thank you!
