### ISSUE TITLE
This is breaking most of the demos

### ISSUE THREAD

**Issue by riteshdalal** [artf/grapesjs-tabs#3]
Most of the plugin demos seems to be broken due to an error on tabs plugin

![Screen Shot 2019-03-25 at 10 54 30 AM](https://user-images.githubusercontent.com/179123/54942562-9a54ae00-4eec-11e9-9fc5-bab2f024fbe9.png)

**Comment by artf** [comment]
Should be fixed here https://github.com/artf/grapesjs-tabs/releases/tag/v0.2.1
