### ISSUE TITLE
Adding tab functionality

### ISSUE THREAD

**Issue by javascriptFan** [artf/grapesjs-tabs#4]
I tried to make adding tab functionality from HTML template but after inserting tab, I added tab content to tab content list. But after changed tab-content-list I can not edit any tab-content anymore.
I added tab content using javascript dynamically to tab-content-list.
Such like this.
`function getCustomTab() {
    return [{
        id: 'tab',
        label: '',
        attributes: {
            class: 'custom-icon flowz-visitor-tab-style-2',
            title: '',
        },
        category: 'Tabs',
        content: 
>                <li>
>                   <div class="square-tab-box" data-id="tab">
>                      <div class="icon motel"></div>
>                      <span class="d-none d-sm-block">Tab</span>
>                   </div>
>                </li>
                ,
            
    }]
}
`
This is what I have done for adding tab content to tab-content list.
`function changeTabId() {
  $('.square-tab-list').each(function () {
      var amount = $(this).find('.square-tab-box').length;
      $(this).find('.square-tab-box').each(function () {
          if ($(this).data('id') == 'tab') {
              $(this).attr('data-id', 'tab' + amount);
              // $(this).parent().parent().css({'display': 'inline'});
              $('.square-tab-content-list').slick('unslick');
              $('.square-tab').append('
              <div data-gjs-type="default" data-highlighttable="1" id="tab${amount}" class="square-tab-content">
                <h5 data-gjs-type="default" data-highlighttable="1" class="d-block d-sm-none mt-3 mb-0 text-center">Things to do</h5>
                <ul data-gjs-type="default" data-highlighttable="1" class="square-tab-content-list">
                    <li data-gjs-type="default" data-highlighttable="1">
                        <div data-gjs-type="default" data-highlighttable="1" class="square-tab-content-img">
                            <img data-gjs-type="default" data-highlighttable="1" src="./images/visit2.jpg">
                        </div>
                        <div data-gjs-type="default" data-highlighttable="1" class="square-tab-content-detail border-box border-light-gray border-1">
                            <div data-gjs-type="default" data-highlighttable="1" class="my-location d-flex align-items-center mb-3">
                                <img data-gjs-type="default" data-highlighttable="1" src="./images/my-location.svg" class="mr-2" width="20">
                                0.7Km
                            </div>
                            <h5 data-gjs-type="default" data-highlighttable="1" class="font-medium">City Hotel Duqm</h5>
                            <p data-gjs-type="default" data-highlighttable="1" class="text-gray">City Hotel Duqm is located between Salalah and Muscat.</p>
                            <div data-gjs-type="default" data-highlighttable="1" class="link">Find Out More</div>
                        </div>
                    </li>
                    <li data-gjs-type="default" data-highlighttable="1">
                        <div data-gjs-type="default" data-highlighttable="1" class="square-tab-content-img">
                            <img data-gjs-type="default" data-highlighttable="1" src="./images/visit3.jpg">
                        </div>
                        <div data-gjs-type="default" data-highlighttable="1" class="square-tab-content-detail border-box border-light-gray border-1">
                            <div data-gjs-type="default" data-highlighttable="1" class="my-location d-flex align-items-center mb-3">
                                <img data-gjs-type="default" data-highlighttable="1" src="./images/my-location.svg" class="mr-2" width="20">
                                3Km
                            </div>
                            <h5 data-gjs-type="default" data-highlighttable="1" class="font-medium">Park Inn by Radisson</h5>
                            <p data-gjs-type="default" data-highlighttable="1" class="text-gray">We welcome our guests in a safe and secure hotel environment</p>
                            <div data-gjs-type="default" data-highlighttable="1" class="link">Find Out More</div>
                        </div>
                    </li>
                    <li>
                        <div data-gjs-type="default" data-highlighttable="1" class="square-tab-content-img">
                            <img data-gjs-type="default" data-highlighttable="1" src="./images/visit1.jpg">
                        </div>
                        <div data-gjs-type="default" data-highlighttable="1" class="square-tab-content-detail border-box border-light-gray border-1">
                            <div data-gjs-type="default" data-highlighttable="1" class="my-location d-flex align-items-center mb-3">
                                <img data-gjs-type="default" data-highlighttable="1" src="./images/my-location.svg" class="mr-2" width="20">
                                1.2Km
                            </div>
                            <h5 data-gjs-type="default" data-highlighttable="1" class="font-medium">Crowne plaza Duqm</h5>
                            <p data-gjs-type="default" data-highlighttable="1" class="text-gray">Get the celebrity treatment with world-class service at Crowne Plaza Duqm</p>
                            <div data-gjs-type="default" data-highlighttable="1" class="link">Find Out More</div>
                        </div>
                    </li>
                </ul>
            </div>'
            );
              return false;
          }
      });
  });
}
`

Can I make a any effective way?
Thanks

javascriptFan

**Comment by artf** [comment]
Please create a live demo of the issue and format your code correctly
