### ISSUE TITLE
Accessibility Issues

### ISSUE THREAD

**Issue by michaelspellacy** [artf/grapesjs-tabs#8]
You might wish to consider making this plugin more accessible. Here is a really excellent and accessible version you can learn from. https://github.com/scottaohara/a11y_tab_widget

**Comment by artf** [comment]
Now the plugin follows [WAI-ARIA Authoring Practices](https://www.w3.org/TR/wai-aria-practices-1.2/#tabpanel) 

https://github.com/artf/grapesjs-tabs/releases/tag/v1.0.6
